### PR TITLE
fixed for latets updaye

### PR DESCRIPTION
**Pull request by e3v3**
base of https://github.com/developer9998/Utilla but they blocked me, also this isnt a modded utilla, legal mods only work in moddeds basically, changed the name of a class, had to make paintbrawl do somestuff otherwise it overflows in the button and changed a traverse thing to data and then did .info

### CODE REVIEW

**Comment by e3v3** [comment]
also dev if you see this, i would make a pr of your repo if you made it so i could 😄

**Comment by e3v3** [comment]
also LEGAL MODS ONLY WORK IN THE MODDED ZONES, I DIDNT CRACK IT

**Comment by iiDk-the-actual** [comment]
I will be using this repository >:3

**Comment by SteveTheAnimator** [comment]
this is skibidi sigma

**Comment by VR-King13** [comment]
so we just have to wait for the approval

**Comment by iyallow99** [comment]
> I will be using this repository >:3

hi ii

**Comment by ghost** [comment]
> I will be using this repository >:3

not ii being silly

**Comment by SteveTheAnimator** [comment]
do mods work in the modded lobbies or am I gonna have to do this
```cs
if((PhotonNetwork.InRoom && PhotonNetwork.CurrentRoom.CustomProperties.ToString().Contains("MODDED")) || !PhotonNetwork.InRoom)
{
  _isModded = true;
} // I wrote this in github lmao

**Comment by dualposition** [comment]
these errors are so skibidi 
image

**Comment by gizmogoat** [comment]
> these errors are so skibidi image

have you tried actually knowing what youre doing and fixing the references

**Comment by SteveTheAnimator** [comment]
> these errors are so skibidi image

REFERENCES RAHHH!!!!!!!

**Comment by HyperDondon** [comment]
> do mods work in the modded lobbies or am I gonna have to do this
> 
> ```cs
> if((PhotonNetwork.InRoom && PhotonNetwork.CurrentRoom.CustomProperties.ToString().Contains("MODDED")) || !PhotonNetwork.InRoom)
> {
>   _isModded = true;
> } // I wrote this in github lmao
> ```

it isnt cracked so ig no

**Comment by HyperDondon** [comment]
> these errors are so skibidi image

you clearly dont know how to build utilla

**Comment by dualposition** [comment]
> > i edge to skibidi
> 
> you clearly dont know how to build utilla

I don't know how to reference shit but devs utilla doesn't need references so I just do that

**Comment by HyperDondon** [comment]
> > > i edge to skibidi
> > 
> > 
> > you clearly dont know how to build utilla
> 
> I don't know how to reference shit but devs utilla doesn't need references so I just do that

scroll down on the utilla readme and do the Libs folder thing and it should work

**Comment by HyperDondon** [comment]
> > > i edge to skibidi
> > 
> > 
> > you clearly dont know how to build utilla
> 
> I don't know how to reference shit but devs utilla doesn't need references so I just do that

references are for being able to interact with gorilla tags existing code by the devs

**Comment by SteveTheAnimator** [comment]
> > do mods work in the modded lobbies or am I gonna have to do this
> > ```cs
> > if((PhotonNetwork.InRoom && PhotonNetwork.CurrentRoom.CustomProperties.ToString().Contains("MODDED")) || !PhotonNetwork.InRoom)
> > {
> >   _isModded = true;
> > } // I wrote this in github lmao
> > ```
> 
> it isnt cracked so ig no

I didn't say it was cracked, dev's fix had an issue where if you went into a modded lobby none of the mods would work (all mods using moddedshitmodejoin)

**Comment by SteveTheAnimator** [comment]
> > > i edge to skibidi
> > 
> > 
> > you clearly dont know how to build utilla
> 
> I don't know how to reference shit but devs utilla doesn't need references so I just do that

pretty sure evelyn has weird directories, I had to replace assembly c# in the references too.

**Comment by Kxcy1** [comment]
how to assemble it

**Pull request closed without merging**
